options:
    deployment:
        type: string
        default: development
        description: Type of deployment, e.g. development, staging, production
    session_secret:
        type: string
        description: Secret key for signing session cookie IDs
    memcache_session_secret:
        type: string
        description: Secret key for encrypting session data stored in memcached
